In [ ]:
def f(x):
  return x**7+x**2+1
x=[0.57735,-0.57735,-0.77459,0,0.77459,0.33998,-0.33998,0.86113,-0.86113,0,0.53846,-0.53846,0.90617,-0.90617,0.23861,-0.23861,0.6612,-0.6612,0.93246,-0.93246]
Lambda=[1,1,0.55555,0.88888,0.55555,0.65214,0.65214,0.34785,0.34785,0.56888,0.47862,0.47862,0.23692,0.23692,0.46791,0.46791,0.36076,0.36076,0.17132,0.17132]
sum=0
n=int(input("Enter n (2 to 6):"))
def add(n):
    if n-1==1:
      a=0
    else:
      a=add(n-1)
    return(n-2+a)

print(add(n))
# count=0
# for i in range(len(x)):
#     a=add(n)
#     count+=1
#     print(Lambda[a],x[a])
#     sum+=Lambda[a]*f(x[a])
#     if count==n:
#       break
# print("Req Integral is",sum)

Enter n (2 to 6):3
1


In [ ]:
import numpy as np 
import numpy.polynomial.laguerre as lib

def f(x):
  import numpy as np
  return np.exp(x)/(x**2+2)    
# Input degree = 2
degree = 2 
# using np.laggauss() method 
res = lib.laggauss(degree)  
# Resulting array of sample point and weight
print (res)
sum=0
for i in range(degree):
  sum+=res[1][i]*f(res[0][i])
print(sum)
print(np.pi/(2*np.sqrt(2)))

(array([0.58578644, 3.41421356]), array([0.85355339, 0.14644661]))
0.9803016223933778
1.1107207345395915


In [ ]:
import numpy.polynomial.laguerre as lib
import numpy as np
def lag_table(degree): 
  table=lib.laggauss(degree)
  return table

def f(x):
  return np.exp(x)/(x**2+2) 

def lag_integrate(degree):
  sum=0
  table=lag_table(degree)
  for i in range(degree):
    sum+=table[1][i]*f(table[0][i])
  return sum

def main():
  exact=np.pi/(2*np.sqrt(2))
  degree=2
  app=lag_integrate(degree)
  while abs(exact-app)>10**(-2):
    degree+=1
    app=lag_integrate(degree)
  return degree,app,exact

degree,app,exact=main()
print("Exact value of integral is",exact)
print("Using Laguerre Quadrature")
print("Approximate value of integral till degree (",degree,") is",app)

Exact value of integral is 1.1107207345395915
Using Laguerre Quadrature
Approximate value of integral till degree ( 27 ) is 1.1008054928174524


In [ ]:
import numpy as np 
import numpy.polynomial.hermite as geek
    
# Input degree = 2
  
degree = 2
     
# using np.laggauss() method 
res = geek.hermgauss(degree) 
  
# Resulting array of sample point and weight
print (res)

(array([-0.70710678,  0.70710678]), array([0.88622693, 0.88622693]))


In [ ]:
import numpy as np 
import numpy.polynomial.legendre as geek
    
# Input degree = 2
  
degree = 2
     
# using np.laggauss() method 
res = geek.leggauss(degree) 
  
# Resulting array of sample point and weight
print (res)

(array([-0.57735027,  0.57735027]), array([1., 1.]))
